### ISSUE TITLE
Plugin error on start

### ISSUE THREAD

**Issue by pwatts6060** [LlemonDuck/dps-calculator#57]
Getting this error with the plugin. If I uninstall and reinstall I still get it.

`2022-06-16 14:05:07 [pool-3-thread-1] WARN  n.r.c.e.ExternalPluginManager - Unable to start or load external plugin "dps-calculator"
java.lang.NoClassDefFoundError: com/google/inject/multibindings/Multibinder
	at com.duckblade.osrs.dpscalc.calc.DpsComputeModule.configure(DpsComputeModule.java:49)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.duckblade.osrs.dpscalc.plugin.DpsCalcPlugin.configure(DpsCalcPlugin.java:28)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at net.runelite.client.plugins.PluginManager.lambda$instantiate$6(PluginManager.java:583)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at net.runelite.client.plugins.PluginManager.instantiate(PluginManager.java:585)
	at net.runelite.client.plugins.PluginManager.loadPlugins(PluginManager.java:394)
	at net.runelite.client.externalplugins.ExternalPluginManager.refreshPlugins(ExternalPluginManager.java:319)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.inject.multibindings.Multibinder
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 22 common frames omitted`

**Comment by LlemonDuck** [comment]
Fixed in 3a9a4d9f630faadc16460e9991287f157003c104 and submitted to hub in runelite/plugin-hub#2850
